### PR TITLE
fix: broken url login + stays at the same profile after login

### PR DESCRIPTION
**Pull request by MichalVasut**

### CODE REVIEW

**Comment by bcaseyrls** [comment]
The server-side handling of the returnURL should be fixed now. Rather than merging a kludge to remove later, perhaps you can just modify your PR to only include the improvement to stay on the profile after login.

**Comment by MichalVasut** [comment]
@bcaseyrls  sure, I would like, but can you please also add `port` in the returned url?

**Comment by bcaseyrls** [comment]
The login is working for me, even if starting on a #name=xxxxx view. But when I login I still land on a view for my own WikiTree ID instead of the one I started on.

I did update the API clientLogin to include the port in the return URL.

**Comment by MichalVasut** [comment]
here is fix: https://github.com/wikitree/wikitree-dynamic-tree/pull/75

description what happened is there

**Pull request merged**
