### PR TITLE
fix: when person is still living, then death date is not shown

### PR DESCRIPTION
**Pull request by MichalVasut**
Fixes: https://github.com/wikitree/wikitree-dynamic-tree/issues/83

also falls back to decade when date is unknown

Still I would like to fix also locations - imho there is an issue with privacy, but I'm not able to decypher those codes
- there is some documentation [privacy fields](https://github.com/wikitree/wikitree-api/blob/main/getProfile.md], but it would be nice to dosument what those levels actually mean - what they influence, ...

### CODE REVIEW

**Comment by harrislineage** [comment]
> * but it would be nice to dosument what those levels actually mean - what they influence, ...

From what I recall - and hopefully Brian will correct me where I am wrong here - but Privacy 20-40 will restrict the gender, relations, dates, and locations. 50 and 60 will return everything. This coincides with the values here: https://www.wikitree.com/wiki/Help:Privacy (60 = Open, 50 = Public, etc.).

**Comment by harrislineage** [comment]
> I connot imagine that King Charles III birthplace is unknown 🤔

Certainly not unknown 😁 



> hmm, as per [Privacy Docs](https://www.wikitree.com/wiki/Help:Privacy) - there are no restrictions for places

It does not appear to be documented, but it should be the exact same for Dates. If the date is not provided due to privacy (e.g., BirthDateDecade is returned and BirthDate is undefuned, null, or however it returns), then the location will also not be provided.

**Comment by MichalVasut** [comment]
Okay, removed Birth location when "unknown" (not provided / private) - there is no needed for some placeholders (`unknown` / `[private]` / ...) in this compact view. Also no need to fetch privacy property - the fields are either provided or not ;-)

IMHO ready for merge

**Comment by bcaseyrls** [comment]
Note that https://github.com/wikitree/wikitree-api/blob/main/getProfile.md documents the numeric value of the Privacy field that corresponds to "Unlisted", "Public", etc.. That provides a data/API-specific supplement to the documentation of intentions for the privacy levels at https://www.wikitree.com/wiki/Help:Privacy. If there's a fault in the handling of Location or other fields wrt Privacy, please post a bug notice to G2G, or an issue to https://github.com/wikitree/wikitree-api and we'll try to get it in the queue to be looked at and fixed.

**Pull request merged**
