### PR TITLE
Refactor to make use of shared/Utils.js: get/setCookie() & show/hideShakingTree()

### PR DESCRIPTION
**Pull request by kayveedw**
Moved views/cc7/js/Utils.js → views/shared/Utils.js
Refactored ancestorLines and stats views to use getCookie(), setCookie(), showShakingTree() and hideShakingTree() from Utils.js

### CODE REVIEW

**Comment by shogenapps** [comment]
By coincidence, my current PR for my Family Group App adds a file named 'utilities.js' to the lib directory.  It has two functions from the app that I thought others may find useful.

**Comment by kayveedw** [comment]
Good point Riël. I was aware that most of the methods were only being used by CC7. I will have another look. Probably, I will reinstate cc7/js/Utils.js minus getCookie(), setCookie(), showShakingTree() and hideShakingTree() which are used by multiple views.

**Comment by kayveedw** [comment]
I have reinstated the file at cc7/js/Utils.js as CC7Utils and renamed the module to CC7Utils. 

getCookie(), setCookie(), showShakingTree() and hideShakingTree() remain in shared/Utils.js. The remaining methods are now only in cc7/js/Utils.js.

**Comment by udjeni** [comment]
@jmegenealogy Could we perhaps get this committed to main ASAP so others (me :) ) can use/add to/expand it?  It does not have to be perfect to start - we can always improve it as we go along. I'm busy seeing if I can make the ALE into a couples-ALE and there are lots of other methods that can happily live in a shared place.

**Comment by jmegenealogy** [comment]
I'm getting some errors re: modules when trying to test on the dev server, so I'm working on finding why.

**Comment by kayveedw** [comment]
Thanks @jmegenealogy I started in /lib and then decided to go with /views/shared. It seems I missed a couple of places.

**Pull request merged**
