### PR TITLE
Replace 0 with 'All' in 'Limit display to generation'

### PR DESCRIPTION
**Pull request by udjeni**
This change also reduces the size of the shaking tree while waiting and corrects errors in the help text.

### CODE REVIEW

**Comment by bcaseyrls** [comment]
@udjeni There are some minor conflicts in this PR. If you merge in the current "main" they should be straight-forward for you to resolve.

**Comment by udjeni** [comment]
Please do not commit this yet -I am still double-checking to see that everything is as it should be.

**Comment by udjeni** [comment]
There definitely are changes here that should not be here. I am busy with a commit to fix it.

**Comment by udjeni** [comment]
OK, the issue with Greg inadvertently overwriting some of my changes has been fixed. This should be OK now for a pull into main.

**Comment by Clarke-11007** [comment]
Mea culpa, mea culpa, mea maxima culpa ....

**Pull request merged**
