### PR TITLE
ALE: Add option to position people relative to their date of birth

### PR DESCRIPTION
**Pull request by udjeni**
* ALE: Add an option to position people relative to their date of birth
* CC7: BioCheck results (and reports) are now included in the excel export.

Until this is merged, both these changes can be test-driven at https://apps.wikitree.com/apps/smit641/dynamic-tree/

### CODE REVIEW

**Comment by udjeni** [comment]
This change will close https://github.com/wikitree/wikitree-dynamic-tree/issues/194

**Comment by jmegenealogy** [comment]
There is some sort of bug in ALE, probably having something to do with profile privacy or lack of dates.

With the "position relative to birth year" option, the tree is going the opposite direction.

image

**Comment by udjeni** [comment]
That's weird since I cater for not finding a birth date. Let me investigate.

**Comment by udjeni** [comment]
The code did not do the right thing if the root profile does not have a birth date. Should be fixed now

**Pull request merged**
