### PR TITLE
People cache

### PR DESCRIPTION
**Pull request by udjeni**
Add a people cache
    
WikiTreeAPI.getPerson() was changed to store newly created Person objects
in a local cache and first look there when any new request is made.
A WikiTreeAPI.makePerson() was introduced to do the same whenever a
Person object needs to be created from a JSON data collection.
    
While this does reduce API calls to some degree in some of the current
view implementaions, it will make a significant difference in upcoming
changes for a couples view.

### CODE REVIEW

**Comment by bcaseyrls** [comment]
Thanks for this work, @udjeni! This is a great start. Storing a cache of person objects so the data can be re-used is something I (and others) have been thinking about. It's a shame that each new view currently has to re-query the API for the same data over and over. I have a few questions about your implementation.

Should we store the peopleCache Map inside ViewRegistry rather than leaving it a scopeless const? Maybe we want some sort of PeopleCache class (or even a more general DataCache class?) that WikiTreeAPI would make use of.

Some views load hundreds (thousands?) of profiles. If a user wanders through one of these views clicking to restart the view at new profiles, etc., the people cache could grow quite large, especially if we're storing all of the profile data. I see you've put a clearCache() call into the ViewRegistry.onPersonDataReceived(). So each new view will wipe things out and start over. That will save the cache size from growing somewhat. However individual views could still grab data for hundreds of profiles (and then never want them again so storing them in the cache doesn't help). And clearing them out when switching views means we don't gain any efficiency of having the same group of profiles for more than one view.

Perhaps the people cache should instead keep an internal count and just limit what it stores. It already queries the API for anything it doesn't have. If we want to store more than N profiles in it, it could dump the older ones. Or some other rubric. Of course this complicates the caching considerably. 

I like that the getPerson() method has logic for isRequestCoveredByPerson. I think it will be common (especially if the cache is used across views) for one feature to get a profile with just a subset of fields. If another feature wants the same profile, but different fields, we still need to do an API call for the data. 

However, I don't quite understand the "richness" value you've assigned. It's only checking for "sub-profiles" - parents, children, spouses. But any of the data fields might be missing. The Surnames view, for example, only requires (and thus only requests) a few profile fields. Other views use far more. If we're going to cache the person data, I think we also need to account for which fields were requested in a more robust way.

**Comment by ben-manes** [comment]
> What I really wanted to use was something like Guava's LoadingCache with size-based eviction, but don't know if there is something like that for JavaScript.

fwiw, [aholstenson/transitory](https://github.com/aholstenson/transitory) is an inspired by caffeine (guava's successor) but I am otherwise not familiar with it.

**Comment by udjeni** [comment]
I agree that the current views do not benefit much from the people cache as
I have implemented it. However, for the couples view, it is essential. Here
is why:

When retrieving a single profile via getPerson, one can get Parents and
Spouses and Children. And we do and construct people objects for all of
them. However, for all but the primary profile, we do NOT have parents,
spouses, nor children. If I now want to provide a drop-down of all spouses
for a person, or all joint children of a couple, I have to go and issue a
getPerson that includes at least the spouses and children for that person
(or both people in a couple). You'll see that this way the same profile
shows up many times in a call to the Person constructor.  Therefore the
people cache is primarily to ensure we only have one profile per person,
but in the process we also reduce the number of API calls.

One could argue that only the couples view needs it, but it would be
awkward (although not impossible I would hope) to implement it only inside
the view. That said, I don't think the proposed cache hurts any of the
other views and we can expand it to cross-view in due course.

**Comment by udjeni** [comment]
I might have made some minor changes to this implementation of the couples view, so will be happy to abandon this PR in favour of the couples view one that is coming down the line. :)

**Comment by udjeni** [comment]
I have decided to withdraw this pull request in favour of moving the people cache into the couples view. If it needs to be shared code, we can move it out at that stage.

**Pull request closed without merging**
