### PR TITLE
Cc7

### PR DESCRIPTION
**Pull request by udjeni**
Add Ian Beacall's CC7 app as a view to the tree apps.  This includes an update to PersonName for which a separate PR has also been posted. This code is running at https://apps.wikitree.com/apps/smit641/cc7/#view=cc7

### CODE REVIEW

**Comment by bcaseyrls** [comment]
Nifty. To work without error (at WikiTree.com with PageSpeed), this requires the fix made to the PersonName class in person_name.js to define window.PersonName. Merging in main should fix that.

I also get an error that the image privacy_private.png does not exist. There's a privacy_private35.png and others, but no privacy_private.png, so when I view a table I get a bunch of 404 errors and broken images.

**Comment by udjeni** [comment]
I have added privacy_private.png and found another missing icon as well (and double checked that they are all there now). I have also added functionality I wanted to add previously, but forgot: a cookie that remembers which CC7 degree was last selected. Degree 7 takes quite a bit of time, so users (like myself :)) may want to just use smaller degrees at different parts of the tree.

**Comment by bcaseyrls** [comment]
I've merged the new CC7 view into the main branch, so it's available for clones of the repository and at https://apps.wikitree.com/apps/wikitree-dynamic-tree. This has not yet been pulled into the version of Tree Apps hosted on the WikiTree website (i.e. https://www.wikitree.com/apps/). There are some challenges with the paths to the images stored inside the view caused by the special needs of that installation. I have a resolution but it needs to be vetted before the new view gets pulled in.

In the meantime, I recommend updating the CC7 view to:
* Remove the use of js.cookie.min.js file from CDN. The wtAPI.cookie function can already get/set cookies (see tree.js) so we should use that instead of loading another module.
* Remove jquery-ui.js and jquery-ui.css. These (moderately large) files are not, I don't think, required. When I tested their removal everything seemed to work. We should avoid pulling in more big JS/CSS if we can (we already load jQuery).

**Comment by udjeni** [comment]
Cool, thanks. I will pay attention to your comments when I get back home on
Monday.  When I tried to remove jquery-ui.js earlier, I got errors saying
$(...).draggable() was not a function, implying it was not in the version
of jquery currently being loaded.  But I will try again since you've had a
different experience.

I agree about the cookies. It was actually on my list of things to do and
then I forgot about them again.

As for the images, the majority of them are the privacy symbol icons that
should already be hosted elsewhere on WikiTree, but I don't know how to get
to them. Then there are only 2 others (if I recall correctly), namely the
house (for family group) and the one used for the timeline link.

**Pull request merged**
