### PR TITLE
Ancestral calendar

### PR DESCRIPTION
**Pull request by bcaseyrls**
The timeline/calendar view only works if the user is logged in, since the code needs to retrieve their watchlist. It also only works for their own profile id. The information div displayed the profile data for any #name=WikiTreeID even though the calendar items themselves were from the user's watchlist. I've added a check on both logged-in status (generating an error) and the profile id (silently redirecting to the user's own name so the info matches).

### CODE REVIEW

**Comment by bcaseyrls** [comment]
This works, but assuming a return value from view.init() is bad... some inits (e.g. Printer Friendly) are async, so the return is a promise. We need something else here.

**Comment by MichalVasut** [comment]
> We need something else here.

Just throw some exception in view and catch it in ViewRegistry...

https://javascript.info/custom-errors

**Comment by bcaseyrls** [comment]
Yes, that's a better solution - bomb out of view.init() with an error caught in in the view.init() call from ViewRegistry. I've done this now in https://github.com/wikitree/wikitree-dynamic-tree/pull/97. 

One issue - the PrinterFriendly view's init() is async. Those functions always return a promise and our try/catch in ViewRegistry won't work. I think we may need to keep View.init() consistent in whether it's async or not (and I'd say not, since all of the views so far except PrinterFriendly are not).

**Comment by MichalVasut** [comment]
> One issue - the PrinterFriendly view's init() is async.

Just checked that and there is no need for it to be async. There is only data loading and the promise can be resolved differently.
Unfortunately I don't know if I will have the time to fix it during the weekend, so if it's the blocker, feel free to rafactor it. Otherwise I'll fix it, but I don't know when.

**Comment by MichalVasut** [comment]
@bcaseyrls just prepared fix for that - https://github.com/wikitree/wikitree-dynamic-tree/pull/101/files

pull request into the ancestral-calendar branch for you - there is also the fix with custom Exception so it made sanse for me to merge those 2 things first and than when it'll work to main

**Pull request closed without merging**
