### PR TITLE
Couples view

### PR DESCRIPTION
**Pull request by udjeni**
The couples tree view combines the trees of two people (i.e. a couple) that are in a some relationship, e.g. in a marriage, or the parents of a child. The tree can be expanded and contracted and it is easy to change the focus of the tree, or to change sub-parts of the tree.

See https://apps.wikitree.com/apps/smit641/test2/#name=Du_Toit-4314&view=couples for this code in action

### CODE REVIEW

**Comment by bcaseyrls** [comment]
I like what you've done to add the spouses for each profile displayed in the tree. It makes it much more dense with information. The addition of the arrows for children works well, as does the arrow to show other spouses. It might be useful to be able to swap which spouse is displayed so that the tree could be expanded from that relationship instead. Perhaps there's a way to do that that I didn't see.

I think the caching here is cumbersome. The "richness" is very feature/view specific. I think we'll need a slightly different approach for something more general. However, this seems to work ok for the new/separate couples view.

A few minor things:

1) I merged your PersonName contribution first, and that caused a conflict in index.js and index.html. That should be easily resolved.

2) As written, this doesn't work with the production WikiTree.com. The use of the PageSpeed module which combines and compresses the JS causes it to break. The problem is that index.html must load cached_person.js first, because CachedPerson is used in the subsequent JS files in views/couplesTree. If you move that script tag to be first in the block:

`   <script src="views/couplesTree/cached_person.js"></script>
    <script src="views/couplesTree/cache_loader.js"></script>
    <script src="views/couplesTree/people_cache.js"></script>
    <script src="views/couplesTree/couples_tree.js"></script>
    <link rel="stylesheet" href="views/couplesTree/couples_tree.css" />
`
Then it works. With those small changes I think the new "couples" view can be merged in.

**Comment by udjeni** [comment]
>It might be useful to be able to swap which spouse is displayed so that the tree could be expanded from that relationship instead.

This is there, but there are restrictions as to when it is possible. If the double right arrow is shown below a spouse's name (i.e. next to its lifespan), it can be clicked to choose that spouse. Or alternatively (this can be used without restrictions), one can just click on the tree symbol to make that spouse the focus of the tree). The restrictions for the right-arrow are:
* It is always possible for the central couple in the tree
* It is not possible in the ancestor tree because that requires too much rebuilding of the tree and who should then be the central couple - may as well just use the "refocus on this person button)
* It is possible in the descendant tree if the spouse being changed is not in bloodline of the central couple. The reason is the same as above, namely if a bloodline spouse is changed, one has to rebuild the whole tree to the right and who should become the central couple?

I agree 100% that the caching solution is NOT a general one as it stands.

I will attend to the conflicts and your index.html comments tomorrow.
Thanks!

**Comment by udjeni** [comment]
I have resolved the conflicts and an loading cached_person first now. Hope this works now on WikiTree.com

**Comment by bcaseyrls** [comment]
I'm sorry, I had to revert this merge. I'm still getting lots of scoping problems when I try to implement these updates to the main branch of the dynamic tree. This happens with or without the PageSpeed module running. I get undefined class errors, even with the re-arranged script tags (and no PageSpeed). I tried putting those into modules and using import/export on the classes. That seemed to work, but then localTesting (from WikiTreeAPI.js) was undefined. 

When I try your code from https://github.com/udjeni/wikitree-dynamic-tree/tree/couples-view, it works ok. But when I merge in these changes to the main tree branch, the code crashes. I haven't done a careful comparison of the files in each repository, so I don't know what's different between them such that one works but the other doesn't.

I need to step back and think about the scoping of the variables and classes we have to understand what's gone wrong. Perhaps you, or another contributor, can spot it before I do.

**Comment by udjeni** [comment]
So what should happen here next?  Anything I should do?

**Pull request merged**
