### PR TITLE
FanChart update: settings menu added (Names and Photos tabs for now)

### PR DESCRIPTION
**Pull request by Clarke-11007**
Thanks to the groundwork laid by Rob Pavey, a new SettingsOption class is created, (modified from his work) and used in the Fan Chart , and implemented for 2 of the 6ish tabs that will be eventually needed to bring forward all the current functionality of the app.

### CODE REVIEW

**Comment by bcaseyrls** [comment]
Looks good. The SettingsOptions file/class may be a good candidate for a /common/ file.

**Comment by MichalVasut** [comment]
Wow, @Clarke-11007 - this looks awesome! But I cannot find out how to access those settings 😅🤔.  There are 2 buttons at the right side of the toolbar (save & settings), but those seems that doesn't work (playing with this in production https://apps.wikitree.com/apps/wikitree-dynamic-tree/#name=Windsor-1&view=fanchart  ).

I though about this in more global way - where you'll define properties (names, types, descriptions, titles,...) and register them with your view - rest will be handled by Views registry - saving, common settings panel,... But that's a lot of work and I don't have time 😔

**Comment by Clarke-11007** [comment]
Hi @MichalVasut  - thanks - the Settings Gear at the far right in the button bar - should popup the Settings panel for you.  I wonder if you tried this before Brian had updated the apps.wikitree.com files?  I just tried it from the link on GitHub and it works as it does on my local version.

Thanks for your other issues raised about the Fractal Tree - those are all valid ones that I noticed but have planned to come back to once I get some more of the basic mechanics working.   There are other issues with the latest FanChart too ... photos on rings further out than 5 gens aren't positioned right, for example.. and probably more.  Getting there ... !

**Comment by MichalVasut** [comment]
Yeah, I've meant the gear and it didn't work, but now, it works as
expected. Thanks.

**Pull request merged**
