### PR TITLE
familyCalendar View

### PR DESCRIPTION
**Pull request by harrislineage**
Add a new [true] calendar view as an alternative to Family Anniversaries.

### CODE REVIEW

**Comment by bcaseyrls** [comment]
This looks great, nice work. The gridded calendar view is a nice way to see these anniversaries. 

When I view my own, however, the page does not work. The getPeople action currently does not allow using a starting person that's private before generating the tree of ancestors/descendants. Possibly this should be updated to allow for profiles with the viewing user in the trusted list (something to discuss in email). A getPerson on the starting person _does_ work. It would be awkward to gather profiles manually instead of using getPeople. Unless/until the API is changed to allow getPeople on private starting profiles, it might be good to catch the error (a status of "Ancestors/Descendant permission denied") in your original getPeople call, and display some sort of note to the user instead of just the blank calendar.

The only other suggestion I have is very minor -- maybe set the control buttons (print, today, arrows) to not print (either via browser print or in your PNG download).  And I might make the day numbers just a bit larger, but that's probably just me.

**Comment by harrislineage** [comment]
Thanks, Brian.

I made some modifications based on your comments.

> When I view my own, however, the page does not work. 

From my testing, it appears that the error message only displays when I am trying to view the private (or unlisted) information for a profile where I am not the PM or on the trusted list. Example, when I try to build a calendar for Casey-1 or Casey-191 I get the error message now as expected.

However, this appears to be working fine for other private and unlisted profiles when I am the PM or that I am on the trusted list for. Example, the calendar builds fine for Harris-5444 (unlisted) and Harris-5447 (private).

It is odd that you would not be able to build on your own profile.

**Comment by harrislineage** [comment]
Also, I have console logging on if you want to review the output on your own profile.

**Review by bcaseyrls — APPROVED** [review]
The calendar works for my own profile now when I'm logged in. I misremembered the code. The starting key can be private if the viewing/requesting user is on the trusted list. That's working for me now. I don't know why it wasn't working before (which led me to make the mistake on permissions). In any case this is working now. The error when viewing a private profile where the use is not on the TL is also working/displaying for me. The larger digits work better for me.

One additional suggestion would be to replace/enhance the link on the entire calendar entry. In addition to linking to the profile page, it might be useful to link to the Special:Relationship or Special:Connection page. My calendar gets full and many of the names are not casually familiar. It would be nice to have a quick way to see who they are / how they're related. 

It might be nice to list the year of the event on the calendar. Instead of just "Birth", perhaps "Birth 1950" or something similar. That would also help distinguish close relatives from distant ones. Or maybe a friendly "58th birthday", but that's not as general as the birth/death labels.

But those are minor changes. I think the calendar looks good, and it's worked for a few different scenarios for me. Nice work.

**Pull request merged**
