### PR TITLE
Updated Timeline to vis.js

### PR DESCRIPTION
**Pull request by harrislineage**
Refactored code and moved to vis.js

### CODE REVIEW

**Review by bcaseyrls — CHANGES_REQUESTED** [review]
The code crashes if the profile has "0000-00-00" as the birth date. This is rare, but it happens. When it does, birth gets set to undefined at the start of buildEvents(), and then later birth.split crashes. I think you need to catch bY == undefined and set birth to "unknown" or something.

**Comment by MichalVasut** [comment]
May I suggest similar visual as FamilySeach has (or had, this is old design and they have new one) - it looks IMHO great, but I would do 1 simple change

image

https://www.familysearch.org/tree/person/timeline/G71M-BYY

On the left side of the line, they have only year, but it would be nice to have complete date there 

The timeline also has some Settings

image

**Comment by harrislineage** [comment]
@bcaseyrls I added a simple condition to set bY as a date of "000-01-01" to clear the error.

I am going to open an issue for better processing of dates.

**Comment by MichalVasut** [comment]
@harrislineage check one of the recent Brian's views (weird name beginning on `A`). There already is date parsing function and IMHO it should be put somewhere outside that view to be used by other functions.

**Comment by bcaseyrls** [comment]
> 

Yes, I agree. Internally we have code for the WikiTree "fuzzy" dates. I think a somewhat generalized date-format function, that accounts for the zeroes, would be useful in the shared Tree.js code.

**Comment by bcaseyrls** [comment]
@harrislineage I merged in your timeline branch updates. However, please note that while the code doesn't crash, the display is still very wonky for me when the user has no birth date. It draws a bar stretching from year 0000 to the present, swamping the width of people with normal life spans.

**Comment by harrislineage** [comment]
@bcaseyrls I noticed that and will address it in the next update.

**Pull request merged**
